### ISSUE TITLE
Weird BLEU

### ISSUE THREAD

**Issue by bangann** [zhuohan123/macaron-net#3]
Hi 

I followed your instruction preprocessing data, then test on the pre-trained model(iwslt14), but get the following results:

pretrained | Generate test with beam=5: BLEU4 = 10.85, 41.1/15.2/6.8/3.3 (BP=1.000, ratio=1.063, syslen=139431, reflen=131156)

I am very confused since I didn't do anything with your code. Could you give me any suggestions on this?

Thanks!

**Comment by bangann** [comment]
And for wmt14, I got the following results of pre-trained model:

> Warning: No built-in rules for language de.
Tokenizer Version 1.1
Language: de
Number of threads: 1
It is not advisable to publish scores from multi-bleu.perl.  The scores depend on your tokenizer, which is unlikely to be reproducible from your paper or consistent across research groups.  Instead you should detokenize then use mteval-v14.pl, which has a standard tokenization.  Scores from multi-bleu.perl can still be used for internal purposes when you have a consistent tokenizer.
pretrained BLEU = 28.91, 60.1/34.6/22.4/15.0 (BP=1.000, ratio=1.011, hyp_len=59943, ref_len=59309)

I guess the last sentence

> pretrained BLEU = 28.91, 60.1/34.6/22.4/15.0 (BP=1.000, ratio=1.011, hyp_len=59943, ref_len=59309)

is from the  blue.txt in the downloaded pre-trained file, not the true result.

I don't know where I'm wrong, please help me

**Comment by bangann** [comment]
Hi,

I trained the small model on iwslt14 dataset instead of using the pre-trained model, and I can reproduce your results. I am still confused about the results of the pre-trained model, but there seems to have no problems with the code.

I also trained the base model on wmt14. When I do testing, although there seems no problem with the blue score (I only trained 1 epoch and get BLUE4=20.12), I still get the following warning

> Warning: No built-in rules for language de.
Tokenizer Version 1.1
Language: de
Number of threads: 1
It is not advisable to publish scores from multi-bleu.perl. The scores depend on your tokenizer, which is unlikely to be reproducible from your paper or consistent across research groups. Instead you should detokenize then use mteval-v14.pl, which has a standard tokenization. Scores from multi-bleu.perl can still be used for internal purposes when you have a consistent tokenizer.

What's the meaning of these warning? There's no such warning when I test on iwslt14. Is that mean the result I got is not correct?

Thx!

**Comment by zhuohan123** [comment]
Did you use the data we provided? Since your own processed data might have some differences in vocabulary and lead to strange outputs

**Comment by zhuohan123** [comment]
I just rechecked the dataset download links and now all of them are working

**Comment by bangann** [comment]
I processed the data myself following your instructions, I will try the data you provided. Thanks!

BTW, is this warning means the result I got is not correct?

> Warning: No built-in rules for language de.
Tokenizer Version 1.1
Language: de
Number of threads: 1
It is not advisable to publish scores from multi-bleu.perl. The scores depend on your tokenizer, which is unlikely to be reproducible from your paper or consistent across research groups. Instead you should detokenize then use mteval-v14.pl, which has a standard tokenization. Scores from multi-bleu.perl can still be used for internal purposes when you have a consistent tokenizer.

**Comment by zhuohan123** [comment]
No, this warning will always be there no matter what your input is

**Comment by bangann** [comment]
OK. Then there are no problems. Thank you!
